openapi: 3.0.4
info:
  title: Replic-Read
  description: Specification for the REST-API that is provided by the Replic_Read backend server.
  version: 1.0.0

paths:
  /auth/signup/:
    post:
      summary: Creates a new account
components:
  schemas:
    # Properties
    uuid:
      type: string
      format: UUID
      example: 2f0ae90d-21a9-4e2f-9192-4632138e7e38
    username:
      type: string
      format: Username
      example: user352
    email:
      type: string
      format: Email
      example: user@example.com

    # Data objects
    AuthUser:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/uuid'
        username:
          $ref: '#/components/schemas/username'
        email:
          $ref: '#/components/schemas/email'
